# Generated by Django 5.1.4 on 2025-01-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date'], 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
    ]
